spring:
  application:
    name: lazuly-auth
  profiles:
    active:
      default
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: ${DB_URI} #jdbc:mysql://localhost/lazuly-users
    username: root
app:
  host: ${HOST}
  signing:
    key: ${JWT_SECRET} #aidafrancoygeorgelosamo
  secret: ${INTERNAL_SECRET} #aidafrancoygeorgelosamo
  emails:
    support: pasutmarcelo@gmail.com, anbenito@yahoo.com.ar
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
server:
  port: 9999