spring:
  application:
    name: lazuly-auth
  profiles:
    active:
      default
app:
  signing:
    key: aidafrancoygeorgelosamo

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
server:
  contextPath: /